comments:
  allowedFields: ["name", "message"]
  requiredFields: ["name", "message"]
  branch: "main"
  path: "_data/comments"
  format: "json"
  moderation: false

  generatedFields:
    date:
      type: date
      options:
        format: "timestamp"  # this generates the timestamp you want

  filename: "comment-{@date}"
