comments:
  allowedFields: ["name", "message"]
  requiredFields: ["name", "message"]
  branch: "main"
  path: "_data/comments/{options.slug}"
  format: "json"
  moderation: false

  generatedFields:
    timestamp:
      type: date
      options:
        format: timestamp

  filename: "comment-{@timestamp}.json"
