comments:
  allowedFields: ["name", "message"]
  requiredFields: ["name", "message"]
  branch: "main"
  path: "_data/comments"
  filename: "comment-{@timestamp}"
  format: "json"
  message: "Add a comment"
